- api/client.php
- bbs/lib/nic.js
- privacy/index.php
- Fix the URL insert bug.
- Add `gethot` interface.
- Add privacy.
> Various Changes on Server Side.

- api/client.php
> Change indent in api/client. Replace tab with space.

- bbs/register/action.php
- bbs/register/index.php
The new CAPUers can now register without the code.
> Remove register code from the form.

- api/jiekouapi.php
> Sql optimization

- .gitignore
> Modified .gitignore for the use of phpMyAdmin

- index/about.php
Change the contact from 抹茶 to 雨荷.
> Update the contact information of daily recruit.

- api/client.php
- api/dbconnector.php
- api/jiekouapi.php
- assets/api/checkuser.php
- assets/api/dbconnector.php
- assets/api/getCalendar.php
- assets/api/main.php
- assets/api/sendsms.php
- bbs/sign/test.php
- bin/DBbackup
- bin/README.md
- bin/conf
- bin/makecron
- bin/tran
- index/borrow.php
- index/download.php
- index/lend.php
- index/main.php
- index/manage.php
1. mv all sql_query(set utf8) to dbconnector
2. backup&scp scripts
> dbconnector&backup script

- .gitignore
There is a `report.html` on the server for monitoring the server. It should be ignored.
> Put report.html into .gitignore.

- assets/api/main.php
Actually, I am doubt about whether we need login functio in the index page.
If we want to seperate bbs and index, this may be the only shared part.
I would like to vote for removing the login feature in index page.
> Fix failed index login.

- api/jiekouapi.php
- bbs/index/index.php
> 网页版只显示十条热点

- api/jiekouapi.php
> Fix move() bug. Sorry for my silly previous change.

- api/client.php
> Image-Upload

- api/client.php
- api/jiekouapi.php
> Personal-Center

- api/jiekouapi.php
> Fix edit-user jiekouapi

- api/client.php
> Revert "Image-Upload"

- api/jiekouapi.php
- bbs/home/message.php
本地测试是OK了的 但是关于正则表达式那块不是很确定 应该没什么问题 谁再看看吧
> Add Quote Notification

- bbs/content/test.php
> Web Editor Image Upload Fix

- index/about.php
> Change contact information.

- index/main.php
It was CAPUUBBS and I fixed it.
> Typo fixed on CAPUBBS for iOS icon.

- index.php
> Remove futaiyuzhuang in footer.

- index/main.php
> Update index videos as links to flash player of YouKu.

- index/about.php
> Update staff list.

- api/client.php
- bbs/lib/mainfunc.php
- lib.php
add conf `sql_mode`
fix api url bug
@huxuan @JeldorPKU @ckcz123
> some bug appears after migration

- assets/api/securimage/securimage.php
- bbs/lib/nic.js
a severe security bug
fix fail to upload images
> Who wrote test.php !!!

- index/main.php
New videos for 2016 summer.
2015 videos are not removed on purpose.
> Update index video.

- bbs/attach/Untitled.html
- lib.php
> fix bug: privilege for mysql

- api/jiekouapi.php
> Add 10.*.*.* as school IP.

- index.php
- index/about.php
> Update contact information.

- index.php
> Add insurance logo.

- index/main.php
> Update 2017 summer videos.

- api/jiekouapi.php
The ipv6 address range is from http://ipv6.pku6.edu.cn/jdjj.htm
> Add PKU ipv6 addresses in function checkinschool

- index/about.php
- index/main.php
> update content of contact info and homepage video

- bbs/content/index.php
Now you can select specific text before you quote, no need of quote+Copy+Paste operation
> Better quote
